# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2
updates:

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    assignees:
      - "XFox111"
    schedule:
      interval: monthly
    rebase-strategy: disabled
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "XFox111"
    schedule:
      interval: monthly
    rebase-strategy: disabled
    open-pull-requests-limit: 20

  - package-ecosystem: "devcontainers"
    directory: "/"
    assignees:
      - "XFox111"
    schedule:
      interval: monthly
    rebase-strategy: disabled
    open-pull-requests-limit: 20
