name: "Release workflow"

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - run: dotnet restore
      - run: dotnet pack

      - name: Drop SimpleOTP
        uses: actions/upload-artifact@v7
        with:
          name: SimpleOTP
          path: libraries/SimpleOTP/bin/Release/EugeneFox.SimpleOTP*.*nupkg

      - name: Drop SimpleOTP.DependencyInjection
        uses: actions/upload-artifact@v7
        with:
          name: SimpleOTP.DependencyInjection
          path: libraries/SimpleOTP.DependencyInjection/bin/Release/EugeneFox.SimpleOTP.DependencyInjection*.*nupkg

  publish-nuget:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USERNAME }}

      - run: dotnet nuget push EugeneFox.SimpleOTP*.*nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

  publish-github:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: dotnet nuget push
        run: dotnet nuget push *.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/xfox111/index.json --skip-duplicate --no-symbols
